name: AdditionalCommands
authors: [Blue_Tree]
version: 1.3
description: adds certain commands (that replys a message with permissions)
main: com.bluetree.additionalcommands.Main
api-version: "1.13"

commands:
  discord:

  additionalcommands:
    aliases: [ac]
  
  website:
  
  discord:
  
  youtube:
    

  